<#
    NetScan 포터블 배포용 zip 생성
    ------------------------------------------------------------
    - NetScan\NetScan.psd1 의 ModuleVersion 을 읽어 dist\NetScan-<버전>-portable.zip 을 만든다.
    - zip 구성 (설치 파일은 포함하지 않음)
        NetScan\            모듈 파일 + portable.flag (설정을 이 폴더에 저장하도록 표시)
        netscan.bat         실행용 배치 파일 (빌드 시 생성)
        README.txt          있을 때만 포함
    - 시스템 설치판(setup.exe)은 Build-Setup.ps1 로 만든다.

    사용법:
        powershell -ExecutionPolicy Bypass -File .\Build-Portable.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$moduleDir = Join-Path $root 'NetScan'
$manifest = Test-ModuleManifest -Path (Join-Path $moduleDir 'NetScan.psd1')
$version = $manifest.Version.ToString()
$packageName = 'NetScan-{0}-portable' -f $version

# ------------------------------------------------------------
# 1) 출력 경로 준비
# ------------------------------------------------------------
$distDir = Join-Path $root 'dist'
if (-not (Test-Path -LiteralPath $distDir)) {
    New-Item -ItemType Directory -Path $distDir | Out-Null
}
$zipPath = Join-Path $distDir ('{0}.zip' -f $packageName)
if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }

# 임시 폴더에 배포본을 구성한 뒤 압축한다 (원본 NetScan 폴더에는 portable.flag 를 넣지 않음)
$stageRoot = Join-Path ([System.IO.Path]::GetTempPath()) ('{0}-{1}' -f $packageName, [guid]::NewGuid().ToString('N'))
$stageDir = Join-Path $stageRoot $packageName
New-Item -ItemType Directory -Path $stageDir -Force | Out-Null

try {
    # --------------------------------------------------------
    # 2) 모듈 파일 복사 (설정 파일 등 매니페스트 FileList 외 파일은 제외)
    # --------------------------------------------------------
    $stageModuleDir = Join-Path $stageDir 'NetScan'
    New-Item -ItemType Directory -Path $stageModuleDir | Out-Null
    foreach ($name in $manifest.FileList) {
        $leaf = Split-Path -Leaf $name
        $src = Join-Path $moduleDir $leaf
        if (-not (Test-Path -LiteralPath $src)) { throw ('모듈 파일이 없습니다: {0}' -f $src) }
        Copy-Item -LiteralPath $src -Destination $stageModuleDir
    }

    # 포터블 표시 파일 : 엔진이 이 파일을 보면 설정을 엔진 폴더에 저장한다
    Set-Content -LiteralPath (Join-Path $stageModuleDir 'portable.flag') -Value 'NetScan portable build' -Encoding ASCII

    # --------------------------------------------------------
    # 3) 실행용 배치 파일 생성 (cmd 는 UTF-8 BOM 을 인식하지 못하므로 ASCII)
    #    엔진이 관리자 권한 승격을 직접 처리하므로 여기서는 호출만 한다.
    # --------------------------------------------------------
    $batLines = @(
        '@echo off'
        'REM NetScan portable launcher (generated by Build-Portable.ps1)'
        'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0NetScan\NetScan.Engine.ps1"'
    )
    Set-Content -LiteralPath (Join-Path $stageDir 'netscan.bat') -Value $batLines -Encoding ASCII

    # --------------------------------------------------------
    # 4) 선택 파일
    # --------------------------------------------------------
    $readme = Join-Path $root 'README.txt'
    if (Test-Path -LiteralPath $readme) {
        Copy-Item -LiteralPath $readme -Destination $stageDir
    }

    # --------------------------------------------------------
    # 5) 압축 (zip 안에 NetScan-<버전>-portable\ 최상위 폴더가 생기도록 폴더째 압축)
    # --------------------------------------------------------
    Compress-Archive -Path $stageDir -DestinationPath $zipPath
    Write-Host ('생성 완료: {0}' -f $zipPath) -ForegroundColor Green
}
finally {
    if (Test-Path -LiteralPath $stageRoot) {
        Remove-Item -LiteralPath $stageRoot -Recurse -Force
    }
}
