<#
    NetScan 모듈 설치 스크립트
    ------------------------------------------------------------
    - 모든 사용자 모듈 경로에 설치한다.
        %ProgramFiles%\WindowsPowerShell\Modules\NetScan\<버전>
      이 경로는 Windows PowerShell 5.1 과 PowerShell 7 이 모두 검색한다.
    - 같은 이름의 기존 설치본은 모두 제거한 뒤 새로 복사한다(설정 파일은 유지).
    - 복사한 파일의 인터넷 다운로드 표시(Zone.Identifier)를 해제한다.
    - cmd 에서도 실행할 수 있도록 %windir%\System32\netscan.bat 을 생성한다.
        · 설치한 모듈의 절대 경로로 Import-Module 하므로 PSModulePath·실행 정책의 영향을 받지 않는다.
        · 같은 이름의 다른 파일이 있으면 덮어쓰지 않는다(-Force 로 강제).
    - 관리자 권한이 없으면 승격된 창으로 다시 실행한다.

    사용법 (압축을 푼 폴더에서):
        powershell -ExecutionPolicy Bypass -File .\Install.ps1
        powershell -ExecutionPolicy Bypass -File .\Install.ps1 -SetExecutionPolicy

    -SetExecutionPolicy : 실행 정책이 Restricted/AllSigned 이면 RemoteSigned(LocalMachine)로 변경
                          (지금 실행 중인 PowerShell 에디션에만 적용됨)
#>
[CmdletBinding()]
param(
    [switch] $SetExecutionPolicy,
    [switch] $Force
)

$ErrorActionPreference = 'Stop'
$ModuleName = 'NetScan'

function Test-Administrator {
    $identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object System.Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
}

# 64비트 System32 경로 (32비트 PowerShell 에서는 System32 가 SysWOW64 로 리디렉션되므로 Sysnative 사용)
function Get-NativeSystem32 {
    if ([Environment]::Is64BitOperatingSystem -and -not [Environment]::Is64BitProcess) {
        return (Join-Path $env:windir 'Sysnative')
    }
    return (Join-Path $env:windir 'System32')
}

# cmd 실행용 배치 파일 판별 : Install.ps1 이 만든 파일(표식 포함) 또는 이전 배포본(powershell netscan)
$script:BatMarker = 'REM Generated by NetScan Install.ps1'
function Test-NetScanBat {
    param([Parameter(Mandatory)][string] $Path)
    $text = Get-Content -LiteralPath $Path -Raw -ErrorAction SilentlyContinue
    if (-not $text) { return $false }
    if ($text.Contains($script:BatMarker)) { return $true }
    $normalized = ($text -replace '\s+', ' ').Trim().ToLowerInvariant()
    return ($normalized -eq '@echo off powershell netscan')
}

# ------------------------------------------------------------
# 1) 관리자 권한 확인 및 자동 승격
# ------------------------------------------------------------
if (-not (Test-Administrator)) {
    Write-Host '설치에는 관리자 권한이 필요합니다. 승격된 창으로 다시 실행합니다...' -ForegroundColor Yellow
    $exe = (Get-Process -Id $PID).Path
    $startArgs = @('-NoExit', '-ExecutionPolicy', 'Bypass', '-File', ('"{0}"' -f $PSCommandPath))
    if ($SetExecutionPolicy) { $startArgs += '-SetExecutionPolicy' }
    if ($Force) { $startArgs += '-Force' }
    try {
        Start-Process -FilePath $exe -Verb RunAs -ArgumentList $startArgs -ErrorAction Stop
    }
    catch {
        Write-Host '권한 승격이 취소되었거나 실패했습니다.' -ForegroundColor Red
    }
    return
}

# ------------------------------------------------------------
# 2) 원본 확인
# ------------------------------------------------------------
$sourceDir = Join-Path $PSScriptRoot $ModuleName
$manifestPath = Join-Path $sourceDir ('{0}.psd1' -f $ModuleName)
if (-not (Test-Path -LiteralPath $manifestPath)) {
    Write-Host ('모듈 원본을 찾을 수 없습니다: {0}' -f $manifestPath) -ForegroundColor Red
    return
}
Get-ChildItem -LiteralPath $PSScriptRoot -Recurse -File | Unblock-File
$manifest = Test-ModuleManifest -Path $manifestPath
$version = $manifest.Version.ToString()

# ------------------------------------------------------------
# 3) 설치 경로 결정 (32비트 PowerShell 에서도 64비트 Program Files 사용)
# ------------------------------------------------------------
$programFiles = if ($env:ProgramW6432) { $env:ProgramW6432 } else { $env:ProgramFiles }
$moduleRoot = Join-Path $programFiles ('WindowsPowerShell\Modules\{0}' -f $ModuleName)
$targetDir = Join-Path $moduleRoot $version

# ------------------------------------------------------------
# 4) 기존 설치본 제거 후 복사
# ------------------------------------------------------------
if (Test-Path -LiteralPath $moduleRoot) {
    Write-Host ('기존 설치본 제거: {0}' -f $moduleRoot) -ForegroundColor DarkGray
    Remove-Item -LiteralPath $moduleRoot -Recurse -Force
}
New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
Copy-Item -Path (Join-Path $sourceDir '*') -Destination $targetDir -Recurse -Force
Get-ChildItem -LiteralPath $targetDir -Recurse -File | Unblock-File

# cmd 실행용 배치 파일 생성 (System32 는 PATH 에 항상 포함됨)
#   - 모듈 이름(netscan) 대신 psd1 절대 경로 + Start-NetScan 을 호출하므로
#     모듈을 못 찾더라도 netscan.bat 이 자기 자신을 다시 부르는 반복이 생기지 않는다.
#   - cmd 는 UTF-8 BOM 을 인식하지 못하므로 ASCII 로 저장한다(내용에 한글 금지).
$batTarget = Join-Path (Get-NativeSystem32) 'netscan.bat'
$installedManifest = Join-Path $targetDir ('{0}.psd1' -f $ModuleName)
$batLines = @(
    '@echo off'
    $script:BatMarker
    'REM Removed by Uninstall.ps1. Do not edit.'
    ('powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Import-Module ''{0}''; Start-NetScan"' -f $installedManifest)
)
$canWrite = (-not (Test-Path -LiteralPath $batTarget)) -or (Test-NetScanBat -Path $batTarget) -or $Force
if ($canWrite) {
    Set-Content -LiteralPath $batTarget -Value $batLines -Encoding ASCII
    Write-Host ('cmd 실행 파일 생성: {0}' -f $batTarget) -ForegroundColor DarkGray
}
else {
    Write-Host ('같은 이름의 다른 파일이 있어 cmd 실행 파일을 만들지 않았습니다: {0}' -f $batTarget) -ForegroundColor Yellow
    Write-Host '  덮어쓰려면 -Force 를 붙여 다시 설치하십시오.' -ForegroundColor Yellow
}

# 설정 폴더 준비 (설정 파일은 첫 저장 때 생성)
$configDir = Join-Path $env:ProgramData $ModuleName
if (-not (Test-Path -LiteralPath $configDir)) {
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null
}

# ------------------------------------------------------------
# 5) 실행 정책 확인
# ------------------------------------------------------------
$policy = Get-ExecutionPolicy
if ($policy -in 'Restricted', 'AllSigned', 'Undefined') {
    if ($SetExecutionPolicy) {
        try {
            Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine -Force
            Write-Host '실행 정책을 RemoteSigned(LocalMachine)로 변경했습니다.' -ForegroundColor Green
        }
        catch {
            Write-Host ('실행 정책을 변경하지 못했습니다(그룹 정책 적용 여부 확인): {0}' -f $_.Exception.Message) -ForegroundColor Red
        }
        $policy = Get-ExecutionPolicy
    }
    if ($policy -in 'Restricted', 'AllSigned', 'Undefined') {
        Write-Host ('주의: 현재 실행 정책({0})에서는 모듈을 불러올 수 없습니다.' -f $policy) -ForegroundColor Yellow
        Write-Host '  다음 중 하나로 허용하십시오.' -ForegroundColor Yellow
        Write-Host '    Set-ExecutionPolicy RemoteSigned -Scope CurrentUser' -ForegroundColor Yellow
        Write-Host '    .\Install.ps1 -SetExecutionPolicy' -ForegroundColor Yellow
    }
}

# ------------------------------------------------------------
# 6) 결과 확인
# ------------------------------------------------------------
$installed = Get-Module -ListAvailable -Name $ModuleName | Where-Object { $_.Version -eq $manifest.Version }
if ($installed) {
    Write-Host ''
    Write-Host ('NetScan {0} 설치 완료: {1}' -f $version, $targetDir) -ForegroundColor Green
    Write-Host '새 PowerShell 또는 cmd 창에서 netscan 을 입력하면 실행됩니다.' -ForegroundColor Cyan
    Write-Host ('설정 파일 위치: {0}' -f (Join-Path $configDir 'scan_tool.config.json')) -ForegroundColor DarkGray
}
else {
    Write-Host '설치 후 모듈을 찾지 못했습니다. PSModulePath 환경 변수를 확인하십시오.' -ForegroundColor Red
}
