; ============================================================
; NetScan 시스템 설치판 - Inno Setup 스크립트
; ------------------------------------------------------------
; - 빌드 : Build-Setup.ps1 (psd1 의 ModuleVersion 을 /DAppVersion 으로 전달)
;          직접 빌드 시 ISCC.exe /DAppVersion=0.4 NetScan.iss
; - 설치 위치
;     모듈     : {commonpf}\WindowsPowerShell\Modules\NetScan\<버전>
;                (Windows PowerShell 5.1 / PowerShell 7 모두 검색하는 경로)
;     cmd 실행 : {sys}\netscan.bat (원본: netscan.bat, 제거 시 자동 삭제)
;     설정     : {commonappdata}\NetScan\scan_tool.config.json (제거 시 삭제 여부 확인)
;     제거기   : {commonpf}\NetScan
;     아이콘   : {commonpf}\NetScan\NetScan.ico (원본: icon\NetScan.ico, 설치된 앱 목록 표시용)
; - 64비트 설치 모드이므로 {sys} = 64비트 System32, {commonpf} = 64비트 Program Files
; - 이 파일은 한글을 포함하므로 UTF-8(BOM) 으로 저장한다.
; ============================================================

#ifndef AppVersion
  #define AppVersion "0.41"
#endif
#define AppName "NetScan"
#define ModuleRoot "{commonpf}\WindowsPowerShell\Modules\NetScan"

[Setup]
; AppId 는 업그레이드/제거 판별 기준이므로 절대 변경하지 않는다.
AppId={{f264a7a2-98a7-47a7-a4d9-a8c563610958}}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher=chauid
AppPublisherURL=https://github.com/chauid/netscan-ps
AppSupportURL=https://github.com/chauid/netscan-ps
AppUpdatesURL=https://github.com/chauid/netscan-ps/releases
AppCopyright=chauid 2026
VersionInfoVersion={#AppVersion}
DefaultDirName={#ModuleRoot}\{#AppVersion}
; 모듈 경로는 고정이어야 하므로 선택 불가, 이전 설치 경로(이전 버전 폴더)도 재사용하지 않음
DisableDirPage=yes
UsePreviousAppDir=no
DisableProgramGroupPage=yes
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0
; 제거기(unins000.exe)는 모듈 폴더가 아닌 별도 폴더에 둔다
UninstallFilesDir={commonpf}\NetScan
UninstallDisplayName={#AppName} {#AppVersion}
; 설치 파일(setup.exe) 아이콘과 설치된 앱 목록(설정 > 앱 / 제어판)에 표시할 아이콘
SetupIconFile=icon\NetScan.ico
UninstallDisplayIcon={commonpf}\NetScan\NetScan.ico
OutputDir=dist
OutputBaseFilename=NetScan-Setup-{#AppVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
#if FileExists(CompilerPath + "Languages\Korean.isl")
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
#endif

[InstallDelete]
; 이전 버전 폴더와 Install.ps1 로 설치했던 기존본을 먼저 정리 (설정 파일은 ProgramData 에 있으므로 유지)
Type: filesandordirs; Name: "{#ModuleRoot}"

[Files]
; 매니페스트 FileList 와 동일하게 명시 (원본 폴더에 생긴 설정 파일 등이 섞이지 않도록)
Source: "NetScan\NetScan.psd1";       DestDir: "{app}"; Flags: ignoreversion
Source: "NetScan\NetScan.psm1";       DestDir: "{app}"; Flags: ignoreversion
Source: "NetScan\NetScan.Engine.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "NetScan\oui.txt";            DestDir: "{app}"; Flags: ignoreversion
; 설치된 앱 목록 아이콘 : 모듈 폴더가 아닌 제거기 폴더에 둔다 (모듈 FileList 와 무관)
Source: "icon\NetScan.ico";           DestDir: "{commonpf}\NetScan"; Flags: ignoreversion
; cmd 실행용 배치 파일 : 같은 이름의 다른 파일이 있으면 CanInstallBat 에서 덮어쓸지 확인
Source: "NetScan\netscan.bat";                DestDir: "{sys}"; Flags: ignoreversion; Check: CanInstallBat

[Dirs]
Name: "{commonappdata}\NetScan"; Flags: uninsneveruninstall

[Tasks]
Name: "execpolicy"; Description: "Windows PowerShell 실행 정책을 RemoteSigned 로 설정 (PowerShell 창에서 netscan 을 쓰려면 필요)"; Flags: unchecked

[Run]
Filename: "{sys}\WindowsPowerShell\v1.0\powershell.exe"; Parameters: "-NoProfile -Command ""Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine -Force"""; StatusMsg: "PowerShell 실행 정책 설정 중..."; Flags: runhidden waituntilterminated; Tasks: execpolicy

[UninstallDelete]
Type: dirifempty; Name: "{#ModuleRoot}"
Type: dirifempty; Name: "{commonpf}\NetScan"

[Code]
var
  BatChecked: Boolean;
  BatAllowed: Boolean;

// cmd 실행용 배치 파일 경로 (64비트 설치 모드이므로 실제 System32)
function GetBatPath: String;
begin
  Result := ExpandConstant('{sys}\netscan.bat');
end;

// NetScan 이 만든 배치 파일인지 판별
//  - 현재 설치판 (netscan.bat)            : "REM NetScan system launcher"
//  - 이전 설치판 / Install.ps1 생성 파일  : "REM Generated by NetScan"
//  - 초기 배포본                          : "powershell netscan" 한 줄
function IsNetScanBat(const Path: String): Boolean;
var
  Content: AnsiString;
  S: String;
begin
  Result := False;
  if not LoadStringFromFile(Path, Content) then
    Exit;
  S := Lowercase(String(Content));
  Result := (Pos('rem netscan system launcher', S) > 0) or
            (Pos('rem generated by netscan', S) > 0) or
            (Pos('powershell netscan', S) > 0);
end;

// [Files] 의 netscan.bat 설치 여부 (Check 함수는 여러 번 호출될 수 있으므로 결과를 한 번만 계산)
function CanInstallBat: Boolean;
var
  BatPath: String;
begin
  if not BatChecked then
  begin
    BatChecked := True;
    BatAllowed := True;
    BatPath := GetBatPath;
    if FileExists(BatPath) and (not IsNetScanBat(BatPath)) then
    begin
      if WizardSilent then
      begin
        Log('Existing netscan.bat was not created by NetScan. Skipped: ' + BatPath);
        BatAllowed := False;
      end
      else
        BatAllowed := MsgBox('NetScan 이 만들지 않은 netscan.bat 이 이미 있습니다.' + #13#10 + BatPath + #13#10#13#10 +
                             '덮어쓰시겠습니까?', mbConfirmation, MB_YESNO) = IDYES;
    end;
  end;
  Result := BatAllowed;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ConfigDir: String;
begin
  // netscan.bat 은 [Files] 로 설치했으므로 제거기가 자동으로 삭제한다.

  // 설정 폴더는 사용자에게 확인 후 삭제 (자동 제거 시에는 유지)
  if (CurUninstallStep = usPostUninstall) and (not UninstallSilent) then
  begin
    ConfigDir := ExpandConstant('{commonappdata}\NetScan');
    if DirExists(ConfigDir) then
      if MsgBox('설정 파일 폴더도 삭제하시겠습니까?' + #13#10 + ConfigDir, mbConfirmation, MB_YESNO) = IDYES then
        DelTree(ConfigDir, True, True, True);
  end;
end;
