<#
    NetScan 모듈 제거 스크립트
    ------------------------------------------------------------
    사용법:
        powershell -ExecutionPolicy Bypass -File .\Uninstall.ps1
        powershell -ExecutionPolicy Bypass -File .\Uninstall.ps1 -RemoveConfig

    -RemoveConfig : %ProgramData%\NetScan (설정 파일) 도 함께 삭제
    %windir%\System32\netscan.bat (cmd 실행 파일) 은 Install.ps1 이 만든 것일 때만 삭제한다.
#>
[CmdletBinding()]
param(
    [switch] $RemoveConfig
)

$ErrorActionPreference = 'Stop'
$ModuleName = 'NetScan'

function Test-Administrator {
    $identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object System.Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
}

# 64비트 System32 경로 (32비트 PowerShell 에서는 System32 가 SysWOW64 로 리디렉션되므로 Sysnative 사용)
function Get-NativeSystem32 {
    if ([Environment]::Is64BitOperatingSystem -and -not [Environment]::Is64BitProcess) {
        return (Join-Path $env:windir 'Sysnative')
    }
    return (Join-Path $env:windir 'System32')
}

# cmd 실행용 배치 파일 판별 : Install.ps1 이 만든 파일(표식 포함) 또는 이전 배포본(powershell netscan)
$script:BatMarker = 'REM Generated by NetScan Install.ps1'
function Test-NetScanBat {
    param([Parameter(Mandatory)][string] $Path)
    $text = Get-Content -LiteralPath $Path -Raw -ErrorAction SilentlyContinue
    if (-not $text) { return $false }
    if ($text.Contains($script:BatMarker)) { return $true }
    $normalized = ($text -replace '\s+', ' ').Trim().ToLowerInvariant()
    return ($normalized -eq '@echo off powershell netscan')
}

if (-not (Test-Administrator)) {
    Write-Host '제거에는 관리자 권한이 필요합니다. 승격된 창으로 다시 실행합니다...' -ForegroundColor Yellow
    $exe = (Get-Process -Id $PID).Path
    $startArgs = @('-NoExit', '-ExecutionPolicy', 'Bypass', '-File', ('"{0}"' -f $PSCommandPath))
    if ($RemoveConfig) { $startArgs += '-RemoveConfig' }
    try {
        Start-Process -FilePath $exe -Verb RunAs -ArgumentList $startArgs -ErrorAction Stop
    }
    catch {
        Write-Host '권한 승격이 취소되었거나 실패했습니다.' -ForegroundColor Red
    }
    return
}

$programFiles = if ($env:ProgramW6432) { $env:ProgramW6432 } else { $env:ProgramFiles }
$moduleRoot = Join-Path $programFiles ('WindowsPowerShell\Modules\{0}' -f $ModuleName)

if (Test-Path -LiteralPath $moduleRoot) {
    Remove-Item -LiteralPath $moduleRoot -Recurse -Force
    Write-Host ('모듈을 제거했습니다: {0}' -f $moduleRoot) -ForegroundColor Green
}
else {
    Write-Host ('설치된 모듈이 없습니다: {0}' -f $moduleRoot) -ForegroundColor DarkGray
}

$batTarget = Join-Path (Get-NativeSystem32) 'netscan.bat'
if (Test-Path -LiteralPath $batTarget) {
    if (Test-NetScanBat -Path $batTarget) {
        Remove-Item -LiteralPath $batTarget -Force
        Write-Host ('cmd 실행 파일을 삭제했습니다: {0}' -f $batTarget) -ForegroundColor Green
    }
    else {
        Write-Host ('NetScan 이 만든 파일이 아니어서 삭제하지 않았습니다: {0}' -f $batTarget) -ForegroundColor Yellow
    }
}

if ($RemoveConfig) {
    $configDir = Join-Path $env:ProgramData $ModuleName
    if (Test-Path -LiteralPath $configDir) {
        Remove-Item -LiteralPath $configDir -Recurse -Force
        Write-Host ('설정 폴더를 삭제했습니다: {0}' -f $configDir) -ForegroundColor Green
    }
}
